[profile.default]
src = 'contracts'
solc = '0.8.17'
out = 'out'
libs = ['lib', 'vendor']
test = 'contracts/v0.8/test'
cache_path = 'foundry-cache'
optimizer = false
evm_version = 'paris'

[fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
